import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderEn from "@/components/header/header-en";
import FooterEn from "@/components/footer/footer-en";
import { Toaster } from "@/components/ui/toaster";
import WhatsAppProvider from "@/components/whatsapp-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "QPMatrix | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <HeaderEn />
        <Toaster />
        {children}
        <WhatsAppProvider />
        <FooterEn />
      </body>
    </html>
  );
}
